import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync(new URL("../admin.html", import.meta.url), "utf8");
const script = readFileSync(new URL("../admin.js", import.meta.url), "utf8");
const configScript = readFileSync(new URL("../site-config.js", import.meta.url), "utf8");
const adminStyles = readFileSync(new URL("../admin.css", import.meta.url), "utf8");
const allScripts = `${script}\n${configScript}`;

assert.match(html, /data-save-button/, "保存按钮需要可被脚本控制禁用状态");
assert.match(html, /data-upload-progress/, "后台需要上传进度条容器");
assert.match(html, /<progress[^>]+data-upload-progress-bar/, "后台需要原生 progress 进度条");
assert.match(script, /confirmCollectionRemoval/, "删除作品集前需要独立确认逻辑");
assert.match(script, /window\.confirm/, "删除作品集需要调用确认弹窗");
assert.match(script, /markDirty/, "修改后需要统一标记未保存状态");
assert.match(script, /markSaved/, "保存完成后需要统一标记已保存状态");
assert.match(script, /saveButton\.disabled = !isDirty \|\| isSaving/, "无新改动或保存中时保存按钮应禁用");
assert.match(script, /已保存到线上网站/, "保存成功反馈需要明确说明已保存到线上网站");
assert.match(allScripts, /XMLHttpRequest/, "上传进度需要使用支持 upload progress 的请求方式");
assert.match(allScripts, /upload\.addEventListener\("progress"/, "上传时需要监听进度事件");
assert.match(configScript, /MAX_UPLOAD_BATCH_BYTES\s*=\s*4\s*\*\s*1024\s*\*\s*1024/, "上传批次需要控制在 Netlify 安全请求大小内");
assert.match(configScript, /createUploadBatches/, "多张图片需要先按总大小拆分批次");
assert.match(configScript, /for \(const batch of batches\)/, "上传批次需要串行发送，避免重新合并成一个大请求");
assert.match(script, /SINGLE_FILE_TOO_LARGE/, "单张超过批次上限时需要给出明确提示");
assert.match(script, /photo-drag-handle/, "照片列表需要显示拖拽把手");
assert.match(script, /dataTransfer\.setData\("text\/plain"/, "原生拖拽需要写入拖拽数据以兼容浏览器");
assert.match(script, /is-drop-before|is-drop-after/, "拖拽时需要显示上下插入位置");
assert.match(script, /data-collection-description/, "后台需要编辑作品集简介字段");
assert.match(html, /data-preview-description/, "后台预览需要包含作品集简介区域");
assert.match(html, /class="preview-site"/, "后台预览需要使用正式站点的完整结构");
assert.match(html, /class="preview-showcase"/, "后台预览需要显示图片与右侧简介布局");
assert.match(html, /data-preview-prev|data-preview-next/, "后台预览需要显示正式站点的切换控制");
assert.match(script, /movePreviewPhoto/, "后台预览需要支持切换当前预览照片");
assert.match(adminStyles, /\[hidden\]\s*\{[^}]*display: none !important/s, "后台隐藏编辑器不能被布局 display 覆盖");
